### ISSUE TITLE
Icons aren’t replacing the default one on the project root/home.

### ISSUE THREAD

**Issue by b0bai** [homerchen19/github-file-icon#59]
![image](https://user-images.githubusercontent.com/14136806/56849823-a1a71700-68f1-11e9-9e77-9c1b8446f946.png)
https://github.com/B0BAI/Gemfire-REST-API-Example

![image](https://user-images.githubusercontent.com/14136806/56849829-c9967a80-68f1-11e9-88a4-5dd40eda7dc1.png)
https://github.com/B0BAI/Server-Sent-Event-Demo

Even my private repo have that issue.

**Comment by B0BAI** [comment]
There is probably a conflict with [Octotree](https://www.octotree.io) plugin.

**Comment by xxhomey19** [comment]
I don't installed Octotree, and those repos look fine from my browser. So the icons look fine if you turn off Octotree?

**Comment by B0BAI** [comment]
Yeah, if Octotree is off everything is fine
![image](https://user-images.githubusercontent.com/14136806/56852209-112bff00-6910-11e9-992f-e5d695775b56.png)

But if I turn it on, it messes up.

![image](https://user-images.githubusercontent.com/14136806/56852191-e6da4180-690f-11e9-80aa-5d2ecfa1f2af.png)

**Comment by xxhomey19** [comment]
Got it. Thanks for reporting this issue.

**Comment by enricoreich** [comment]
I don't have this issue with octotree but with [refined github](https://github.com/sindresorhus/refined-github).

**Comment by janat08** [comment]
https://github.com/sindresorhus/refined-github/issues/1993#issuecomment-487423210

**Comment by bfred-it** [comment]
This has been fixed in https://github.com/sindresorhus/refined-github/commit/fedcb021f6c99cb811a0b8ec52dd29f6a9102df9

**Comment by FranklinYu** [comment]
@B0BAI Why close it? Is it fixed?

**Comment by B0BAI** [comment]
No, not fix. I wonder if someone will give an update on the issue. I have since decided to not the github-file-icon lib.

**Comment by homerchen19** [comment]
Just tested on my chrome. This issue seems to be fixed now.
I installed both extensions, and everything works pretty well.

<img width="345" alt="Screen Shot 2020-06-19 at 18 19 48" src="https://user-images.githubusercontent.com/12113222/85122736-a0ede480-b259-11ea-82fc-47a61c36c73e.png">

**Comment by FranklinYu** [comment]
I thought the intention was to leave this issue open until the two bullet points from @fregante are implemented? Currently it was *worked around* on RGH side (according to the comment above), but it’s brittle. For example it still doesn’t work for me.
